export default [
  {
    id: 1,
    firstName: 'Mathilda',
    lastName: 'West',
    level: 'D0A Simulations',
    quantity: 1,
    quality: 0,
    initiative: 0.3,
    communication: 0,
    professionalism: 0,
    integration: 0,
  },
  {
    id: 2,
    firstName: 'Mittie',
    lastName: 'Bowers',
    level: 'D0B Apprenticeships',
    quantity: 1,
    quality: 0,
    initiative: 0.4,
    communication: 0.1,
    professionalism: 0,
    integration: 0,
  },
  {
    id: 3,
    firstName: 'Adekunle',
    lastName: 'Gold',
    level: 'D0B Apprenticeships',
    quantity: 0,
    quality: 1,
    initiative: 0.8,
    communication: 0,
    professionalism: 0,
    integration: 1,
  },
  {
    id: 4,
    firstName: 'Hallie',
    lastName: 'James',
    level: 'D0A Simulations',
    quantity: 0,
    quality: 0,
    initiative: 1,
    communication: 0.4,
    professionalism: 0,
    integration: 0,
  },
  {
    id: 5,
    firstName: 'Estella',
    lastName: 'Graves',
    level: 'D0A Simulations',
    quantity: 1,
    quality: 0,
    initiative: 1,
    communication: 0.9,
    professionalism: 0,
    integration: 1,
  },
  {
    id: 6,
    firstName: 'Genevieve',
    lastName: 'Black',
    level: 'D0B Apprenticeships',
    quantity: 1,
    quality: 1,
    initiative: 0.3,
    communication: 0.4,
    professionalism: 1,
    integration: 0,
  },
  {
    id: 7,
    firstName: 'Gavin',
    lastName: 'Berry',
    level: 'D0A Simulations',
    quantity: 0.4,
    quality: 0,
    initiative: 0.4,
    communication: 1,
    professionalism: 0,
    integration: 1,
  },
  {
    id: 8,
    firstName: 'Tonny',
    lastName: 'Gibbs',
    level: 'D0B Apprenticeships',
    quantity: 0,
    quality: 1,
    initiative: 1,
    communication: 0.3,
    professionalism: 1,
    integration: 1,
  },
  {
    id: 9,
    firstName: 'Chase',
    lastName: 'Wright',
    level: 'D0B Apprenticeships',
    quantity: 0.1,
    quality: 0.4,
    initiative: 0.4,
    communication: 1,
    professionalism: 0,
    integration: 1,
  },
  {
    id: 10,
    firstName: 'Hallie',
    lastName: 'Sullivan',
    level: 'D0A Simulations',
    quantity: 0.2,
    quality: 0.1,
    initiative: 1,
    communication: 0,
    professionalism: 0,
    integration: 1,
  },
];
